version: "3"

services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    user: vscode
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    working_dir: /app
    volumes:
      - /mnt:/mnt
      - ~/Downloads:/home/vscode/Downloads
      - ~/.cache:/home/vscode/.cache
      - ~/.vscode-server:/home/vscode/.vscode-server
      - ~/.vscode-server-insiders:/home/vscode/.vscode-server-insiders
      - ~/.codeium/:/home/vscode/.codeium
      - ~/.config/nvim:/home/vscode/.config/nvim
      - ~/.local/share:/home/vscode/.local/share
      - ~/.bun/install:/home/vscode/.bun/install
      # ====================================================================
      # - ./ComfyUI:/workspace/ComfyUI
    ports:
      - 8080:8080
    command: python main.py --listen=0.0.0.0
