name: Publish Docker image

on:
  push:
    branches: [ "main" ]
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Node
        uses: actions/setup-node@v3
      - run: npm install -g @devcontainers/cli
      - name: Build image
        run: >
          devcontainer build
            --workspace-folder .
            --config ./.devcontainer/pytorch-devcontainer.jsonc
            --image-name huodon/pytorch-devcontainer:118
            --platform linux/amd64
      - name: Push image
        run: docker push huodon/pytorch-devcontainer:118
